In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
pwd

'C:\\Users\\saivi'

In [3]:
dataset =pd.read_csv('finalproject.csv')

In [4]:
dataset.head()

AGE  HEART BEAT  SYSTOLIC  DIASTOLIC  SUGAR  ALERT
0   18          60        90         50     90      0
1   18          60        91         51     91      0
2   18          60        92         52     92      0
3   18          60        93         53     93      0
4   18          60        94         54     94      0

In [18]:
x= dataset.iloc[:99149,:5].values

In [19]:
type(x)

numpy.ndarray

In [20]:
x

array([[ 18,  60,  90,  50,  90],
       [ 18,  60,  91,  51,  91],
       [ 18,  60,  92,  52,  92],
       ...,
       [ 40,  94, 178,  94, 204],
       [ 40,  94, 179,  95, 205],
       [ 40,  94, 180,  96, 206]], dtype=int64)

In [21]:
y= dataset.iloc[:99149,-1:].values

In [22]:
y

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [23]:
from sklearn.model_selection import train_test_split           
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [24]:
import keras 
from keras.models import Sequential 
from keras.layers import Dense 

In [25]:
model=Sequential()

In [26]:
model.add(Dense(input_dim=5,init="random_uniform",activation="relu",output_dim=3))

C:\Users\saivi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=5, activation="relu", units=3, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [27]:
model.add(Dense(output_dim=3,init="random_uniform",activation="relu"))

C:\Users\saivi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=3, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [28]:
model.add(Dense(output_dim=1,init="random_uniform",activation="sigmoid"))

C:\Users\saivi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [29]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [30]:
model.fit(x_train,y_train,epochs=100,batch_size=100)

Epoch 1/100
79318/79318 [==============================] - 2s 31us/step - loss: 0.4492 - acc: 0.8052
Epoch 2/100
79318/79318 [==============================] - 2s 20us/step - loss: 0.2752 - acc: 0.9188
Epoch 3/100
79318/79318 [==============================] - 1s 19us/step - loss: 0.2251 - acc: 0.9249
Epoch 4/100
79318/79318 [==============================] - 2s 21us/step - loss: 0.1943 - acc: 0.9315
Epoch 5/100
79318/79318 [==============================] - 2s 25us/step - loss: 0.1721 - acc: 0.9365
Epoch 6/100
79318/79318 [==============================] - 1s 17us/step - loss: 0.1543 - acc: 0.9416
Epoch 7/100
79318/79318 [==============================] - 1s 17us/step - loss: 0.1391 - acc: 0.9474
Epoch 8/100
79318/79318 [==============================] - 2s 19us/step - loss: 0.1257 - acc: 0.9526
Epoch 9/100
79318/79318 [==============================] - 1s 19us/step - loss: 0.1136 - acc: 0.9580
Epoch 10/100
79318/79318 [==============================] - 2s 21us/step - loss: 0.1016 - a

79318/79318 [==============================] - 2s 24us/step - loss: 0.0016 - acc: 0.9996
Epoch 81/100
79318/79318 [==============================] - 2s 26us/step - loss: 5.3632e-04 - acc: 1.0000
Epoch 82/100
79318/79318 [==============================] - 2s 24us/step - loss: 0.0016 - acc: 0.9996
Epoch 83/100
79318/79318 [==============================] - 2s 23us/step - loss: 4.8885e-04 - acc: 1.0000
Epoch 84/100
79318/79318 [==============================] - 2s 26us/step - loss: 7.0940e-04 - acc: 1.0000
Epoch 85/100
79318/79318 [==============================] - 3s 37us/step - loss: 5.6311e-04 - acc: 1.0000: 0s - loss: 6.05
Epoch 86/100
79318/79318 [==============================] - 3s 39us/step - loss: 4.8275e-04 - acc: 1.0000
Epoch 87/100
79318/79318 [==============================] - 3s 35us/step - loss: 7.2465e-04 - acc: 1.0000
Epoch 88/100
79318/79318 [==============================] - 3s 32us/step - loss: 0.0021 - acc: 0.9994
Epoch 89/100
79318/79318 [============================

In [31]:
model.save("finalprojecttest.h5")

In [32]:
dataset.shape

(99148, 6)

In [33]:
y_pred=model.predict(x_test)

In [34]:
l = len(y_pred)
l

19830

In [52]:
for i in range(l):
    if(y_pred[i] > 0.5):
        y_pred[i] =int(1)
    else:
        y_pred[i]=int(0)


In [53]:
y_pred=y_pred.astype(int)

In [54]:
y_test[8]

array([0], dtype=int64)

In [55]:
y_pred[1]

array([0])

In [56]:
from keras.models import load_model
model = load_model("finalprojecttest.h5")

In [57]:
from sklearn.metrics import confusion_matrix

In [58]:
matrix = confusion_matrix(y_test, y_pred)

In [59]:
matrix

array([[    0, 10204],
       [ 9626,     0]], dtype=int64)

In [61]:
pred=model.predict(np.array([[22,70,120,80,150]]))
if(pred > 0.5):
    pred =int(1)
else:
    pred =int(0)
pred    

0

In [ ]:
y_test

In [ ]:
y_pred


In [ ]:
x_test[0]